apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: origin
  name: origin
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      run: origin
  template:
    metadata:
      labels:
        run: origin
    spec:
      containers:
      - image: quay.io/openshift/origin-console:v3.11.0
        imagePullPolicy: Always
        name: console
        env:
        - name: BRIDGE_USER_AUTH
          value: disabled # must be one of: oidc, disabled
        - name: BRIDGE_K8S_MODE
          value: off-cluster
        - name: BRIDGE_K8S_MODE_OFF_CLUSTER_ENDPOINT
          value: K8S_ENDPOINT
        - name: BRIDGE_K8S_MODE_OFF_CLUSTER_SKIP_VERIFY_TLS
          value: "true"
        - name: BRIDGE_K8S_AUTH
          value: bearer-token
        - name: BRIDGE_K8S_AUTH_BEARER_TOKEN
          value: K8S_SECRET_TOKEN
        ports:
        - containerPort: 9000
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: origin-dashboard
  namespace: kube-system
  labels:
    run: origin
spec:
  type: NodePort
  ports:
  - port: 9000
    targetPort: 9000
    nodePort: 31900
    protocol: TCP
    name: http
  - port: 8443
    targetPort: 8443
    nodePort: 31844
    protocol: TCP
    name: api
  selector:
    run: origin
